runtime:
  version: "4.0.0"
  framework: "pulser"
  compatibility: "4.x"

agents:
- agent_name: claude_desktop
  capabilities:
  - task_delegation
  - non_executing
  - sql_queries
  name: ClaudeDesktop
  type: coordinator
  memory_tags: ["task_history", "delegation_patterns"]
  permissions: ["read", "coordinate"]
- agent_name: bruno
  capabilities:
  - shell_root
  - docker_ops
  - privileged_exec
  name: Bruno
  path: ./agents/bruno/bruno-agent.yaml
  type: executor
  memory_tags: ["execution_history", "docker_state"]
  permissions: ["execute", "privileged"]
- agent_name: pulser_cli
  capabilities:
  - orchestration
  - etl_pipelines
  - agent_coordination
  name: PulserCLI
  path: ./persistence/pulser-task-runner.sh
  type: orchestrator
  memory_tags: ["pipeline_state", "orchestration_logs"]
  permissions: ["orchestrate", "coordinate"]
- agent_name: jampacked
  capabilities:
  - creative_analysis
  - award_prediction
  - csr_scoring
  name: JamPacked
  path: ./mcp-integration/analyze-with-jampacked-handler.js
  type: analyzer
  memory_tags: ["analysis_cache", "scoring_models"]
  permissions: ["analyze", "score"]
- agent_name: claude_desktop_drive_extractor
  capabilities:
  - google_drive_extraction
  - awards_data_processing
  name: ClaudeDesktopDriveExtractor
  path: ./mcp-integration/claude-desktop-drive-extractor.js
  type: extractor
  memory_tags: ["extraction_state", "drive_metadata"]
  permissions: ["extract", "read"]
- agent_name: agent_relay
  capabilities:
  - task_routing
  - queue_management
  name: AgentRelay
  path: ./mcp-integration/agent_relay.py
  type: dispatcher
  memory_tags: ["routing_rules", "queue_state"]
  permissions: ["route", "manage_queue"]
- agent_name: data_fabcon
  capabilities:
  - data_profiling
  - schema_analysis
  - quality_assessment
  name: DataFabcon
  path: ./src/data_fabcon/__init__.py
  type: profiler
  memory_tags: ["profile_cache", "schema_history"]
  permissions: ["profile", "analyze_data"]
google_drive:
  extraction_method: claude_desktop
  folder_id: 0AJMhu01UUQKoUk9PVA
mcp:
  config_path: /Users/tbwa/Documents/GitHub/mcp-sqlite-server/config/server-config-local.json
  db_path: /Users/tbwa/Documents/GitHub/mcp-sqlite-server/data/database.sqlite
  enabled: true
  server: sqlite
monitoring:
  alert_thresholds:
    cpu_usage: 80
    error_rate: 5
    memory_usage: 85
    response_time: 5000
  retention_days: 30
results:
  analyses_table: jampacked_analyses
  awards_table: campaign_awards
  csr_table: csr_assessments
  scores_table: jampacked_scores
services:
  api_server:
    path: ./api/jampacked-api-server.js
    port: 3001
  performance_monitor:
    path: ./mcp-integration/performance-monitoring.js
  websocket_server:
    path: ./mcp-integration/realtime-notifications.js
    port: 8765
sources:
- name: Scout Dashboard PRD v4.1.0
  path: scout_dashboard_prd.json
  searchable: true
  tags:
  - prd
  - documentation
  - scout dashboard
  type: prd
task_delegation:
  analysis: jampacked
  exec: bruno
  extraction: claude_desktop_drive_extractor
  orchestrate: pulser_cli
task_queue:
  max_retries: 3
  priority_levels: 10
  table: agent_task_queue
versioning:
  enabled: true
  reproducibility_snapshots: true
  track_lineage: true
