global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'jampacked-production'
    
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          
# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"
  
# Scrape configurations
scrape_configs:
  # JamPacked Core API metrics
  - job_name: 'jampacked-core'
    static_configs:
      - targets: ['jampacked-core:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    
  # Pattern Discovery Workers
  - job_name: 'pattern-workers'
    static_configs:
      - targets: ['pattern-discovery-worker:9090']
    metrics_path: '/metrics'
    
  # Cultural Analysis Workers  
  - job_name: 'cultural-workers'
    static_configs:
      - targets: ['cultural-worker:9090']
    metrics_path: '/metrics'
    
  # Multimodal Workers
  - job_name: 'multimodal-workers'
    static_configs:
      - targets: ['multimodal-worker:9090']
    metrics_path: '/metrics'
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    
  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
      
  # NVIDIA GPU metrics (if available)
  - job_name: 'gpu'
    static_configs:
      - targets: ['nvidia-gpu-exporter:9835']